version: '2'
services:
  proxyvm:
    image: dorissschoi/proxyvm
    hostname: proxyvm
    container_name: proxyvm    
    ports:
      - 8007:1337
      - 8008:8080
    volumes:
      - ${COMPOSEROOT}/proxyvm/config/env/development.coffee:/usr/src/app/config/env/development.coffee
      - ${COMPOSEROOT}/proxyvm/config/env/development.coffee:/usr/src/app/config/env/production.coffee
      - ${COMPOSEROOT}/proxyvm/www/js/config/development.coffee:/usr/src/app/www/js/config/development.coffee
      - ${COMPOSEROOT}/proxyvm/www/js/config/development.coffee:/usr/src/app/www/js/config/production.coffee
      - /etc/ssl/certs:/etc/ssl/certs
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      - ${COMPOSEROOT}/proxyvm/entrypoint.sh:/usr/src/app/entrypoint.sh
      - ${COMPOSEROOT}/proxyvm:/usr/src/app
      - ${COMPOSEROOT}/activiti-client:/tmp/activiti-client
      - ${COMPOSEROOT}/proxyvm:/tmp/bu
      
    env_file:
      - ./.env
    external_links:
      - todoactiviti_mongo
    networks:
      - activiti_default
      - todoactivitimongo_default
    entrypoint: top -b -d 1000          

networks:
  activiti_default:
    external: true
  todoactivitimongo_default:
    external: true     