version: '2'
services:
  vagrant_mongo:
    image: mongo
    ports:
      - 27017
    command: mongod --directoryperdb 
    environment:
      SERVICE_NAME: vagrant_mongo

  vagrant:
    image: twhtanghk/vagrantvm
    depends_on: 
      - vagrant_mongo
    privileged: true
    network_mode: host
    ports:
      - "2200-2250:2200-2250"
      - "8000-8050:8000-8050"
    volumes:
      - /lib/modules:/lib/modules
      - /var/run/libvirt:/var/run/libvirt
      - /var/lib/libvirt:/var/lib/libvirt
    env_file: 
      - ./.env
      - ../.env
