version: '2'
services:
  vagrant_mongo:
    image: mongo
    ports:
      - 27017
    command: mongod --directoryperdb 

  vagrant:
    image: twhtanghk/vagrantvm
    depends_on: 
      - vagrant_mongo
    privileged: true
    ports:
      - "2200-2250:2200-2250"
      - "8000-8050:8000-8050"
    volumes:
      - /lib/modules:/lib/modules
      - /dev/vboxdrv:/dev/vboxdrv
    env_file: 
      - ./.env
      - ../.env
