version: '2'
services:
  ssh:
    image: twhtanghk/ssh
    ports:
      - 1337
    networks:
      - nginx_default
    environment:
      SERVICE_NAME: ssh
    env_file:
      - ./.env.ssh
      
  vagrant_mongo:
    image: mongo
    ports:
      - 27017
    command: mongod --directoryperdb 
    environment:
      SERVICE_NAME: vagrant_mongo

  vagrant:
    image: dorissschoi/vagrantvm
    depends_on: 
      - vagrant_mongo
    privileged: true
    network_mode: host
    volumes:
      - /lib/modules:/lib/modules
      - /var/run/libvirt:/var/run/libvirt
      - /var/lib/libvirt:/var/lib/libvirt
      - ${COMPOSEROOT}/vagrantvm/data:/usr/src/app/config/vagrant
    env_file: 
      - ./.env
      - ../.env

networks:
  nginx_default:
    external: true
